name: PHP CI

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Update autoload
        run: composer dump-autoload
      - name: Run PHP_CodeSniffer
        run: composer lint
      - name: Run tests
        run: composer test